FROM php:7.2-fpm

WORKDIR /home/

RUN apt-get -y update \
    && apt-get install -y libzip-dev zip libmemcached-dev \
    && apt-get install -y vim \
    && apt-get install -y htop \
    && rm -rf /var/lib/apt/lists/*

RUN docker-php-ext-install zip opcache mysqli pdo_mysql pdo

RUN docker-php-ext-enable mysqli \
    && docker-php-ext-enable opcache \
    && docker-php-ext-enable pdo_mysql \
    && pecl install memcached 
    
EXPOSE 9000